### ISSUE TITLE
how to run the code

### ISSUE THREAD

**Issue by yanghq13** [dbacchet/magnum-bazel#1]
hello 
i am find the code of glfw building by BAZEL, but i don't know how to run it.
could you give more detail about run the code?

**Comment by dbacchet** [comment]
Hi! 

after you build the supporting libraries with the `build_magnum.sh` script, you can run:
```
bazel build //...
```
and it will build for you the example app that is in this repository.
To run it you can then use bazel again:
```
bazel run //sample:scenegraph_example
```
or run the executable directly with:
```
./bazel-bin/sample/scenegraph_example
```

I also added the same explanation to the main README.md file (and updated the imgui and imguizmo versions to 1.83...)

**Comment by yanghq13** [comment]
Thanks！
